src/Entity/Membres.php
<?php

namespace App\Entity;

use App\Repository\MembresRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: MembresRepository::class)]
class Membres
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_membre = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank(message: 'Le nom est obligatoire')]
    #[Assert\Regex(
        pattern: '/^[a-z]+$/i',
        htmlPattern: '^[a-zA-Z]+$',
        message: 'Le nom doit contenir uniquement des lettres'
    )]
    #[Assert\Length(
        min: 2,
        minMessage: '2 caractères minimum',
    )]
    private ?string $nom_membre = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank(message: 'Le login est obligatoire')]
    private ?string $login_membre = null;

    public function getIdMembre(): ?int
    {
        return $this->id_membre;
    }

    public function getNomMembre(): ?string
    {
        return $this->nom_membre;
    }

    public function setNomMembre(string $nom_membre): static
    {
        $this->nom_membre = $nom_membre;

        return $this;
    }

    public function getLoginMembre(): ?string
    {
        return $this->login_membre;
    }

    public function setLoginMembre(string $login_membre): static
    {
        $this->login_membre = $login_membre;

        return $this;
    }
}

src/Form/MembresType.php
<?php

namespace App\Form;

use App\Entity\Membres;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MembresType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_membre')
            ->add('login_membre')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Membres::class,
        ]);
    }
}

src/Controller/MembresController.php
<?php

namespace App\Controller;

use App\Entity\Membres;
use App\Form\MembresType;
use App\Repository\MembresRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

final class MembresController extends AbstractController
{
    #[Route('/', name: 'app_membres')]
    public function index(MembresRepository $membresRepository): Response
    {
        $membres = $membresRepository->findAll();

        return $this->render('membres/index.html.twig', [
            'controller_name' => 'MembresController',
            'membres' => $membres
        ]);
    }

    #[Route('/new', name: 'app_membres_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $membre = new Membres();
        $form = $this->createForm(MembresType::class, $membre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($membre);
            $entityManager->flush();
            $this->addFlash('success', 'le membre a bien été ajouté');

            return $this->redirectToRoute('app_membres', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('membres/new.html.twig', [
            'membre' => $membre,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_membres_delete', methods: ['POST'])]
    public function delete(Request $request, Membres $membre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$membre->getIdMembre(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($membre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_membres', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/edit', name: 'app_membres_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Membres $membre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MembresType::class, $membre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_membres', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('membres/edit.html.twig', [
            'membre' => $membre,
            'form' => $form,
        ]);
    }


}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        {% block stylesheets %}
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
            <link rel="stylesheet" href="css/style.css">
        {% endblock %}

        {% block javascripts %}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
        <div class="bg"></div>
        <div class="bg bg2"></div>
        <div class="bg bg3"></div>
        <div class="content"></div>
        {% block body %}{% endblock %}
    </body>
</html>

templates/membres/_delete_form.html.twig
<form method="post" action="{{ path('app_membres_delete', {'id': membre.idMembre}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer ce membre?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ membre.idMembre) }}">
    <button class="btn btn-outline-danger">Supprimer</button>
</form>

templates/membres/_form.html.twig
{{ form_start(form) }}
  <div class="container-fluid w-75">
    <div class="mb-3 row align-items-center">
      <label class="col-sm-3 col-form-label">{{ form_label(form.nom_membre) }}</label>
      <div class="col-sm-9">
        {{ form_widget(form.nom_membre, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.nom_membre) }}
      </div>
    </div>

    <div class="mb-3 row align-items-center">
      <label class="col-sm-3 col-form-label">{{ form_label(form.login_membre) }}</label>
      <div class="col-sm-9">
        {{ form_widget(form.login_membre, {'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.login_membre) }}
      </div>
    </div>
  </div>
  <div class="mt-3">
    <button type="submit" class="btn btn-outline-light">{{ button_label|default('Enregistrer') }}</button>
    <a href="{{ path('app_membres') }}" class="btn btn-outline-light ms-2">Retour</a>
  </div>
{{ form_end(form) }}

templates/membres/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un membre{% endblock %}

{% block body %}
    <h1 class="display-1 text-center mb-5 text-white">Modification</h1>

    <div class="container-fluid w-50 border p-4 shadow-lg text-center text-white border-5 rounded-3 mb-3">
        {{ include('membres/_form.html.twig', {'form': form}) }}
    </div>

{% endblock %}

templates/membres/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Membres{% endblock %}

{% block body %}
    <h1 class="display-1 text-center text-white">Liste des membres</h1>
<div class="container-fluid mb-3 w-75 "> 
    <table class="table mt-5 shadow-lg bg-primary bg-opacity-100 rounded-5 table-shadow-boost">
        <thead>
            <tr class="text-center ">
                <th>Id</th>
                <th>nom</th>
                <th>login</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for membre in membres %}
            <tr class="text-center">
                <td>{{ membre.idMembre }}</td>
                <td>{{ membre.nomMembre|upper }}</td>
                <td>{{ membre.loginMembre|capitalize }}</td>
                <td class="d-flex gap-3 justify-content-center">
                    <a href="{{ path('app_membres_edit', {'id': membre.idMembre}) }}" class="btn btn-outline-primary">Modifier</a>
                    {{ include('membres/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="text-center w-100"><a href="{{ path('app_membres_new') }}" class="btn btn-outline-success mt-2 mb-2">Creer un nouveau Membre</a></td>
            </tr>
        </tfoot>
    </table>
</div>
{% endblock %}

templates/membres/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau Membres{% endblock %}

{% block body %}
    <h1 class="display-1 text-center mb-5 text-white" >Créer un nouveau membre</h1>

    <div class="container-fluid w-50 border p-4 shadow-lg text-center text-white order border-5 rounded-3">
        {{ include('membres/_form.html.twig', {'form': form}) }}
    </div>

    

{% endblock %}